version: '3.8'

services:
  db:
    image: postgres:15
    container_name: crm_postgres
    environment:
      POSTGRES_USER: crmuser
      POSTGRES_PASSWORD: crmpass
      POSTGRES_DB: crmdev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - crmnet

volumes:
  pgdata:


networks:
  crmnet:
